apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: element-gateway:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: RedisConnection
          value: "redis:6379"
        - name: IdentityServiceInternalUrl
          value: "http://identity-service:8080"
        - name: ReverseProxy__Clusters__identity-cluster__Destinations__destination1__Address
          value: "http://identity-service:8080"
        - name: ReverseProxy__Clusters__element-cluster__Destinations__destination1__Address
          value: "http://element-service:8080"
        - name: ReverseProxy__Clusters__order-cluster__Destinations__destination1__Address
          value: "http://order-service:8080"
        - name: ReverseProxy__Clusters__notification-cluster__Destinations__destination1__Address
          value: "http://notification-service:8080"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
