apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - identity-service.yaml
  - element-service.yaml
  - order-service.yaml
  - notification-service.yaml
  - payment-service.yaml
  - shipment-service.yaml
  - gateway.yaml
  - ingress.yaml
