apiVersion: v1
kind: Service
metadata:
  name: {{ include "element-market.fullname" . }}-gateway
spec:
  ports:
    - port: {{ .Values.services.gateway.port }}
  selector:
    app: element-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: element-gateway
spec:
  selector:
    matchLabels:
      app: element-gateway
  template:
    metadata:
      labels:
        app: element-gateway
    spec:
      containers:
        - name: gateway
          image: {{ .Values.services.gateway.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://+:{{ .Values.services.gateway.port }}
            - name: RedisConnection
              value: {{ .Values.global.redis | quote }}
            - name: RabbitMQ__Host
              value: {{ include "element-market.fullname" . }}-rabbitmq
            - name: IdentityServiceInternalUrl
              value: http://{{ include "element-market.fullname" . }}-identity:{{ .Values.services.identity.port }}
            - name: ElementServiceInternalUrl
              value: http://{{ include "element-market.fullname" . }}-element:{{ .Values.services.element.port }}
          ports:
            - containerPort: {{ .Values.services.gateway.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.services.gateway.port }}
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.services.gateway.port }}
            initialDelaySeconds: 5
