apiVersion: v1
kind: Service
metadata:
  name: {{ include "element-market.fullname" . }}-postgres
spec:
  ports:
    - port: {{ .Values.global.postgres.port }}
  selector:
    app: element-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: element-postgres
spec:
  selector:
    matchLabels:
      app: element-postgres
  template:
    metadata:
      labels:
        app: element-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.infrastructure.postgres.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.global.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.global.postgres.password | quote }}
          ports:
            - containerPort: {{ .Values.global.postgres.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "element-market.fullname" . }}-redis
spec:
  ports:
    - port: 6379
  selector:
    app: element-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: element-redis
spec:
  selector:
    matchLabels:
      app: element-redis
  template:
    metadata:
      labels:
        app: element-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.infrastructure.redis.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "element-market.fullname" . }}-rabbitmq
spec:
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: management
  selector:
    app: element-rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: element-rabbitmq
spec:
  selector:
    matchLabels:
      app: element-rabbitmq
  template:
    metadata:
      labels:
        app: element-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.infrastructure.rabbitmq.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
          ports:
            - containerPort: 5672
            - containerPort: 15672
