import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, BookOpen, Check, FlaskConical, Lightbulb, LockKeyhole, Plus, RotateCcw, Search, Sparkles, X } from 'lucide-react';
import Seo from '../components/Seo';
import AtlasVisual from '../components/AtlasVisual';
import { useScience, type ScientificCompound } from '../services/science';
import { availableMaterials, combine, discover, equationText, formulaText, hint, loadProgress, materials, materialById, recipes, saveProgress, stages, unlockedElements, type LabRecipe } from '../services/lab';

function ResultVisual({id}:{id:string}){const {data}=useScience<ScientificCompound>('compounds',id);return <AtlasVisual compact formula={formulaText(materialById[id].formula)} structure={data?.media?.structure}/>;}
const pathFor=(id:string)=>`/${materialById[id].kind==='element'?'element':'compound'}/${id.toLowerCase()}`;
export default function Laboratory(){
  const [params]=useSearchParams();const requested=params.get('material');
  const [initial]=useState(()=>{try{return loadProgress(window.localStorage);}catch{return {discovered:[],persistent:false};}});
  const [found,setFound]=useState(initial.discovered);const [persistent,setPersistent]=useState(initial.persistent);
  const [slots,setSlots]=useState<(string|null)[]>(()=>requested&&availableMaterials(initial.discovered).includes(requested)?[requested,null]:[null,null]);
  const [result,setResult]=useState<LabRecipe|null>(null);const [message,setMessage]=useState('');const [tip,setTip]=useState('');
  const [query,setQuery]=useState('');const [filter,setFilter]=useState<'all'|'element'|'compound'>('all');
  const [resetConfirm,setResetConfirm]=useState(false);
  const available=availableMaterials(found);const unlocked=unlockedElements(found);const nextStage=stages.find(s=>s.at>found.length);
  const fold=(s:string)=>s.toLocaleLowerCase('tr').replace(/ı/g,'i').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const shown=materials.filter(m=>available.includes(m.id)&&(filter==='all'||m.kind===filter)&&fold(`${m.name} ${m.formula}`).includes(fold(query)));
  const setProgress=(next:string[])=>{setFound(next);try{setPersistent(saveProgress(window.localStorage,next));}catch{setPersistent(false);}};
  const choose=(id:string,index?:number)=>{if(!available.includes(id))return;setSlots(current=>{const next=[...current];next[index??(current[0]===null?0:1)]=id;return next;});setMessage('');setTip('');};
  const mix=()=>{
    if(!slots[0]||!slots[1])return;
    const match=combine(slots[0],slots[1],found);setTip('');setResult(match??null);
    if(!match){setMessage('Bu eşleşme için oyunda bir keşif yok. Başka iki kart dene.');return;}
    const wasKnown=found.includes(match.result);const next=discover(found,match.result);const added=unlockedElements(next).filter(id=>!unlocked.includes(id));
    setProgress(next);setMessage(`${wasKnown?'Bunu daha önce keşfettin':'Yeni keşif'}: ${materialById[match.result].name}.${added.length?` Yeni elementler açıldı: ${added.map(id=>materialById[id].name).join(', ')}.`:''}`);
  };
  return <main className="science-detail lab-page">
    <Seo title="Laboratuvar · ElementAPI" description="Altı elementle başlayarak 18 gerçek bileşiği keşfet. Kartları birleştir, yeni elementler aç ve bilimsel bağlantıları öğren." path="/lab"/>
    <header className="lab-heading"><div><p className="science-eyebrow"><FlaskConical size={15}/> KEŞİF LABORATUVARI</p><h1>Birleştir. Merak et. Keşfet<span>.</span></h1><p>İki madde kartı seç. Yeni bileşikler buldukça laboratuvarın büyüsün.</p></div><div className="lab-progress"><strong>{found.length}<span> / {recipes.length}</span></strong><span>bileşik keşfedildi</span><progress value={found.length} max={recipes.length} aria-label="Keşif ilerlemesi"/></div></header>
    <div className="lab-stage-path" aria-label="Element açılma aşamaları">{stages.map((stage,i)=><div key={stage.at} className={found.length>=stage.at?'is-unlocked':''}>{found.length>=stage.at?<Check size={15}/>:<LockKeyhole size={14}/>}<span>{i===0?'Başlangıç':`${stage.at} keşif`}</span><strong>{stage.elements.join(' · ')}</strong></div>)}</div>
    {requested&&materialById[requested]&&!available.includes(requested)&&<p className="science-notice">{materialById[requested].name} henüz açılmadı. Keşiflere devam ederek bu karta ulaşabilirsin.</p>}
    {!persistent&&<p className="science-notice">Tarayıcı kaydı kullanılamıyor. Bu oturumda oynamaya devam edebilirsin; sayfa kapanınca ilerleme kaybolabilir.</p>}
    <div className="lab-layout"><section className="lab-inventory" aria-label="Madde kartları"><header><h2>Malzemelerin</h2><span>{available.length} kart</span></header><label className="lab-search"><Search size={16}/><input type="search" placeholder="Malzeme ara…" aria-label="Malzeme ara" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="lab-filters">{([['all','Tümü'],['element','Elementler'],['compound','Bileşikler']] as const).map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="lab-materials">{shown.map(m=><button key={m.id} className={`lab-material is-${m.kind} ${slots.includes(m.id)?'is-picked':''}`} draggable onDragStart={e=>{e.dataTransfer.setData('text/plain',m.id);e.dataTransfer.effectAllowed='copy';}} onClick={()=>choose(m.id)} aria-label={`${m.name} kartını seç`}><strong>{formulaText(m.formula)}</strong><span>{m.name}</span><small>{m.kind==='element'?'Element':'Keşfedildi'}</small></button>)}</div>{!shown.length&&<p className="science-data-note">Bu filtrede malzeme yok. Farklı bir arama dene.</p>}<p className="lab-inventory-note">Kartları seç veya deney alanına sürükle. Malzemeler tükenmez.</p></section>
    <section className="lab-bench" aria-label="Deney alanı"><div className="lab-bench-top"><p className="science-eyebrow">DENEY ALANI</p><button className="lab-clear" onClick={()=>{setSlots([null,null]);setResult(null);setMessage('');setTip('');}}><RotateCcw size={14}/> Alanı temizle</button></div><div className="lab-slots">{slots.map((id,index)=><div className="lab-slot-wrap" key={index}>{index===1&&<Plus className="lab-plus" size={22}/>}<button className={`lab-slot ${id?'is-filled':''}`} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';}} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.getData('text/plain'),index);}} onClick={()=>{setSlots(current=>current.map((v,i)=>i===index?null:v));}} aria-label={`${index+1}. seçim yuvası${id?`: ${materialById[id].name}, seçimi kaldır`:': boş'}`}>{id?<><strong>{formulaText(materialById[id].formula)}</strong><span>{materialById[id].name}</span><small><X size={12}/> Kaldır</small></>:<><Plus size={25}/><span>{index+1}. maddeyi seç</span><small>Kartı buraya bırakabilirsin</small></>}</button></div>)}</div><div className="lab-bench-actions"><button className="lab-combine" disabled={!slots[0]||!slots[1]} onClick={mix}><FlaskConical size={18}/> Birleştir <ArrowRight size={17}/></button><button className="lab-hint" onClick={()=>{const recipe=hint(found);setTip(recipe?`${materialById[recipe.inputs[0]].name} ile ${materialById[recipe.inputs[1]].name} arasında bir bağlantı var.`:'Bütün keşifleri tamamladın.');}}><Lightbulb size={17}/> İpucu</button></div>
    <p className="lab-announcement" role="status" aria-live="polite">{tip||message||'İlk bağlantın için hidrojen ve oksijeni seçebilirsin.'}</p>
    {result?<article className="lab-result" key={result.result}><div className="lab-result-heading"><div><p className="science-eyebrow"><Sparkles size={14}/> KEŞİF KAYDI</p><h2>{materialById[result.result].name}</h2><strong>{formulaText(materialById[result.result].formula)}</strong></div><ResultVisual id={result.result}/></div><span className={`lab-rule-label ${result.reaction?'is-reaction':''}`}>{result.reaction?'Kaynaklı tepkime':'Keşif eşleştirmesi'}</span><p>{result.explanation}</p>{result.reaction&&<details className="lab-reaction"><summary>Denklem ve bilimsel açıklama</summary><p className="lab-equation">{equationText(result.reaction.equation)}</p><p>{result.reaction.conditions}</p><p>Yan ürünler: {result.reaction.byproducts.length?result.reaction.byproducts.join(', '):'Bu denklemde başka kimyasal ürün gösterilmiyor.'}</p><a href={result.reaction.source} target="_blank" rel="noreferrer">Tepkime kaynağı <ArrowUpRight size={13}/></a></details>}<div className="lab-result-actions"><Link to={`/compound/${result.result}`}>Bilimsel kaydı aç <ArrowUpRight size={15}/></Link><button onClick={()=>{setSlots([result.result,null]);setMessage('Yeni bileşiğinin yanına başka bir kart seç.');}}>Bu kartla devam et <ArrowRight size={15}/></button></div></article>:<div className="lab-empty-result"><div aria-hidden="true">H<span>—</span>O<span>—</span>H</div><h2>Her bağlantının bir hikâyesi var.</h2><p>Keşif kartlarında maddenin formülünü, özelliklerini ve kaynaklarını bulacaksın.</p></div>}
    <p className="lab-science-note">Kartlar madde türlerini temsil eder; miktar veya deney tarifi değildir. “Kaynaklı tepkime” ve “keşif eşleştirmesi” farklı bilgi türleridir.</p></section></div>
    <section className="lab-notebook"><header><div><p className="science-eyebrow"><BookOpen size={15}/> KEŞİF DEFTERİN</p><h2>{found.length===18?'Laboratuvar tamamlandı!':'Biriken küçük keşifler.'}</h2><p>{found.length===18?'18 bileşiği keşfettin. Artık her birinin bilimsel hikâyesini inceleyebilirsin.':nextStage?`${nextStage.at-found.length} yeni keşifle ${nextStage.elements.join(', ')} açılacak.`:'Bütün elementler açık. Son bileşikleri bulmaya devam et.'}</p></div><button className="lab-reset" onClick={()=>setResetConfirm(true)}>İlerlemeyi sıfırla</button></header><div className="lab-notebook-grid">{recipes.map(r=>{const known=found.includes(r.result);return known?<Link key={r.result} to={pathFor(r.result)}><Check size={14}/><strong>{formulaText(materialById[r.result].formula)}</strong><span>{materialById[r.result].name}</span></Link>:<div key={r.result} className="is-locked"><LockKeyhole size={14}/><strong>?</strong><span>Keşfedilmeyi bekliyor</span></div>;})}</div><p className="science-data-note">Keşifler yalnız bu tarayıcıda saklanır. Kredi bakiyeni veya mağaza envanterini etkilemez.</p>{resetConfirm&&<div className="lab-reset-confirm" role="alert"><p>Bu tarayıcıdaki keşif defteri silinecek. Baştan başlamak istiyor musun?</p><button onClick={()=>{setProgress([]);setSlots([null,null]);setResult(null);setMessage('Yeni keşif defteri açıldı.');setResetConfirm(false);}}>Evet, sıfırla</button><button onClick={()=>setResetConfirm(false)}>Vazgeç</button></div>}</section>
  </main>;
}

