// <auto-generated />
using System;
using Element.Services.Element.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Element.Services.Element.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ElementDbContext))]
    [Migration("20260603064330_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Element.Services.Element.Core.Entities.ChemicalElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AtomicNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PricePerGram")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("ReservedWeightGrams")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("StockWeightGrams")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("ChemicalElements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a2b56e4-4a4b-4b13-b5bb-76226f3cbca1"),
                            AtomicNumber = 79,
                            Name = "Gold",
                            PricePerGram = 75.25m,
                            ReservedWeightGrams = 0m,
                            StockWeightGrams = 1000m,
                            Symbol = "Au"
                        },
                        new
                        {
                            Id = new Guid("1a2b56e4-4a4b-4b13-b5bb-76226f3cbca2"),
                            AtomicNumber = 47,
                            Name = "Silver",
                            PricePerGram = 1.15m,
                            ReservedWeightGrams = 0m,
                            StockWeightGrams = 10000m,
                            Symbol = "Ag"
                        },
                        new
                        {
                            Id = new Guid("2a2b56e4-4a4b-4b13-b5bb-76226f3cbca3"),
                            AtomicNumber = 3,
                            Name = "Lithium",
                            PricePerGram = 0.18m,
                            ReservedWeightGrams = 0m,
                            StockWeightGrams = 50000m,
                            Symbol = "Li"
                        },
                        new
                        {
                            Id = new Guid("3a2b56e4-4a4b-4b13-b5bb-76226f3cbca4"),
                            AtomicNumber = 78,
                            Name = "Platinum",
                            PricePerGram = 35.80m,
                            ReservedWeightGrams = 0m,
                            StockWeightGrams = 500m,
                            Symbol = "Pt"
                        },
                        new
                        {
                            Id = new Guid("4a2b56e4-4a4b-4b13-b5bb-76226f3cbca5"),
                            AtomicNumber = 29,
                            Name = "Copper",
                            PricePerGram = 0.009m,
                            ReservedWeightGrams = 0m,
                            StockWeightGrams = 1000000m,
                            Symbol = "Cu"
                        });
                });

            modelBuilder.Entity("Element.Services.Element.Core.Entities.ElementPriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ElementSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ElementSymbol");

                    b.ToTable("PriceHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
