// <auto-generated />
using Element.Services.Element.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Element.Services.Element.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ElementDbContext))]
[Migration("20260621220000_AddStockReservations")]
partial class AddStockReservations
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Target model captured in ElementDbContextModelSnapshot.
    }
}
