import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight, Download, FileJson, Search } from 'lucide-react';
import { scienceUrl, useScience, type JsonValue, type ScientificRecord } from '../services/science';
import Seo from './Seo';

const labels: Record<string, string> = {
  precautionary_codes: 'Önlem kodları', signal_words: 'Uyarı sözcükleri',
  names: 'Adlandırma', tr: 'Türkçe', en: 'İngilizce', la: 'Latince', de: 'Almanca', iupac: 'IUPAC adı', classification: 'Sınıflandırma', period: 'Periyot', group: 'Grup', block: 'Blok', series: 'Seri', category: 'Kategori', cas_number: 'CAS numarası', appearance: 'Görünüm',
  atomic_properties: 'Atomik özellikler', atomic_mass: 'Atom kütlesi (u)', standard_atomic_weight_reported: 'Standart atom ağırlığı · kaynak gösterimi', standard_atomic_weight_uncertainty: 'Atom ağırlığı belirsizliği', electron_configuration: 'Elektron dizilimi', short: 'Kısa gösterim', full: 'Tam gösterim', term_symbol: 'Terim sembolü', electrons_per_shell: 'Kabuk başına elektron', valence_electrons: 'Değerlik elektronları', oxidation_states: 'Yükseltgenme basamakları', common: 'Yaygın', rare: 'Nadir', electronegativity: 'Elektronegatiflik', pauling: 'Pauling', allen: 'Allen', allred_rochow: 'Allred–Rochow', mulliken: 'Mulliken', ionization_energies_kj_mol: 'İyonlaşma enerjileri (kJ/mol)', electron_affinity_kj_mol: 'Elektron ilgisi (kJ/mol)', radii_pm: 'Yarıçaplar (pm)', atomic_empirical: 'Atomik · deneysel', atomic_calculated: 'Atomik · hesaplanan', covalent_single_bond: 'Kovalent · tek bağ', covalent_double_bond: 'Kovalent · çift bağ', covalent_triple_bond: 'Kovalent · üçlü bağ', van_der_waals: 'Van der Waals',
  thermodynamic_properties: 'Termodinamik', standard_state: 'Standart hâl', melting_point: 'Erime noktası', boiling_point: 'Kaynama noktası', k: 'Kelvin (K)', c: 'Santigrat (°C)', triple_point: 'Üçlü nokta', critical_point: 'Kritik nokta', temperature_k: 'Sıcaklık (K)', pressure_kpa: 'Basınç (kPa)', pressure_mpa: 'Basınç (MPa)', density_g_cm3: 'Yoğunluk (g/cm³)', reported: 'Kaynakta bildirilen', conditions: 'Ölçüm koşulları', stp: 'STP koşullarında', liquid_at_mp: 'Erime noktasında sıvı', enthalpy_of_fusion_kj_mol: 'Erime entalpisi (kJ/mol)', enthalpy_of_vaporization_kj_mol: 'Buharlaşma entalpisi (kJ/mol)', specific_heat_capacity_j_g_k: 'Özgül ısı kapasitesi (J/g·K)', molar_heat_capacity_j_mol_k: 'Molar ısı kapasitesi (J/mol·K)',
  mechanical_properties: 'Mekanik özellikler', mohs_hardness: 'Mohs sertliği', vickers_hardness_mpa: 'Vickers sertliği (MPa)', brinell_hardness_mpa: 'Brinell sertliği (MPa)', youngs_modulus_gpa: 'Young modülü (GPa)', youngs_modulus_reported: 'Young modülü · koşullarıyla (GPa)', shear_modulus_gpa: 'Kayma modülü (GPa)', shear_modulus_reported: 'Kayma modülü · koşullarıyla (GPa)', bulk_modulus_gpa: 'Hacim modülü (GPa)', poissons_ratio: 'Poisson oranı', speed_of_sound_m_s: 'Ses hızı (m/s)',
  electromagnetic_and_optical: 'Elektromanyetik ve optik', electrical_resistivity_ohm_m: 'Elektrik özdirenci (Ω·m)', electrical_conductivity_s_m: 'Elektrik iletkenliği (S/m)', thermal_conductivity_w_m_k: 'Isıl iletkenlik (W/m·K)', thermal_expansion_coefficient_um_m_k: 'Isıl genleşme (µm/m·K)', magnetic_ordering: 'Manyetik düzen', curie_temperature_k: 'Curie sıcaklığı (K)', refractive_index: 'Kırılma indisi', crystallography: 'Kristal yapı', structure_name: 'Yapı adı', space_group_number: 'Uzay grubu numarası', space_group_symbol: 'Uzay grubu sembolü', lattice_parameters_pm: 'Örgü parametreleri (pm; açılar °)', a: 'a', b: 'b', alpha: 'α', beta: 'β', gamma: 'γ', abundance: 'Doğada bulunma', universe_mass_percent: 'Evrende kütlece (%)', solar_system_mass_percent: 'Güneş sisteminde kütlece (%)', crust_mg_kg: 'Yer kabuğunda (mg/kg)', ocean_mg_l: 'Okyanusta (mg/L)', human_body_mass_percent: 'İnsan vücudunda kütlece (%)', history: 'Tarihçe', discovered_year: 'Keşif yılı', discovery_reported: 'Kaynakta keşif bilgisi', discoverers: 'Keşfedenler', etymology: 'Köken', isotopes: 'İzotoplar', mass_number: 'Kütle numarası', exact_mass_da: 'Kesin kütle (Da)', exact_mass_reported: 'Kesin kütle · belirsizliğiyle', abundance_percent: 'Doğal bolluk (%)', abundance_fraction_reported: 'Bolluk oranı · belirsizliğiyle', half_life: 'Yarı ömür', spin_parity: 'Spin / parite', decay_mode: 'Bozunma biçimi',
  identifiers: 'Kimlik ve yapı', pubchem_cid: 'PubChem CID', cas: 'CAS', inchi: 'InChI', inchi_key: 'InChIKey', smiles: 'SMILES', connectivity_smiles: 'Bağlantı SMILES', molecular_properties: 'Moleküler özellikler', molecular_formula: 'Molekül formülü', molecular_weight_g_mol: 'Molar kütle (g/mol)', monoisotopic_mass_da: 'Monoizotopik kütle (Da)', formal_charge: 'Formal yük', xlogp: 'XLogP', topological_polar_surface_area_a2: 'Topolojik polar yüzey alanı (Å²)', hydrogen_bond_donors: 'Hidrojen bağı vericileri', hydrogen_bond_acceptors: 'Hidrojen bağı alıcıları', rotatable_bonds: 'Dönebilen bağlar', complexity: 'Moleküler karmaşıklık', physical_properties: 'Fiziksel özellikler', density: 'Yoğunluk', solubility: 'Çözünürlük', dissociation_constants: 'Ayrışma sabitleri', safety: 'Güvenlik ve toksikoloji', ghs: 'GHS sınıflandırması', hazard_codes: 'Tehlike kodları', pictograms: 'Piktogram kodları', nfpa_704: 'NFPA 704', health: 'Sağlık', flammability: 'Yanıcılık', instability: 'Kararsızlık', special: 'Özel', toxicology: 'Toksikoloji', ld50_oral_rat_mg_kg: 'LD₅₀ · sıçan, oral (mg/kg)', ld50_oral_mouse_mg_kg: 'LD₅₀ · fare, oral (mg/kg)', reported_values: 'Kaynaklarda bildirilen deneyler', occupational_exposure_limits: 'Mesleki maruziyet sınırları', osha_pel_mg_m3: 'OSHA PEL (mg/m³)', acgih_tlv_mg_m3: 'ACGIH TLV (mg/m³)', bioactivity_and_pharmacology: 'Biyoaktivite ve farmakoloji', target_proteins: 'Hedef proteinler', mechanism_of_action: 'Etki mekanizması', metabolism: 'Metabolizma', elimination_half_life_hours: 'Eliminasyon yarı ömrü (saat)', mechanism_sources: 'Etki mekanizması kaynakları', metabolism_sources: 'Metabolizma kaynakları', half_life_sources: 'Yarı ömür kaynakları', sources: 'Kaynaklar', note: 'Veri notu', value: 'Bildirilen değer', source: 'Kaynak', source_url: 'Kaynağı aç', name: 'Ad', uniprot_id: 'UniProt', action: 'Etki'
};
const populated = (v: JsonValue): boolean => v !== null && (Array.isArray(v) ? v.some(populated) : typeof v === 'object' ? Object.values(v).some(populated) : v !== '');
const textValue = (v: JsonValue) => typeof v === 'number' ? new Intl.NumberFormat('tr-TR', { maximumSignificantDigits: 14 }).format(v) : String(v);
function Value({ value, showMissing, context }: { value: JsonValue; showMissing: boolean; context?: string }) {
  if (value === null) return <span className="science-missing">Veri yok</span>;
  if (typeof value !== 'object') {
    if (typeof value === 'string' && /^https?:\/\//.test(value)) return <a className="science-source-link" href={value} target="_blank" rel="noreferrer">Kaynağı incele <ArrowUpRight size={12} /></a>;
    return <>{textValue(value)}</>;
  }
  if (Array.isArray(value)) {
    if (!value.length) return <span className="science-missing">Bu kayıtta veri bulunmuyor</span>;
    if (value.every(v => v === null || typeof v !== 'object')) return <span className="science-values">{value.map((v, i) => <span key={i}>{v == null ? '—' : textValue(v)}</span>)}</span>;
    return <div className="science-records">{value.map((v, i) => <div key={i} className="science-subrecord"><Value value={v} showMissing={showMissing} /></div>)}</div>;
  }
  const entries = Object.entries(value).filter(([, v]) => showMissing || populated(v));
  if (!entries.length) return <p className="science-missing">Bu bölüm için doğrulanmış veri henüz eklenmedi.</p>;
  return <dl className="science-properties">{entries.map(([key, v]) => <div key={key} className={v && typeof v === 'object' ? 'science-property-group' : ''}><dt>{context === 'lattice_parameters_pm' && key === 'c' ? 'c' : labels[key] ?? key.replace(/_/g, ' ')}</dt><dd><Value value={v} showMissing={showMissing} context={key} /></dd></div>)}</dl>;
}
export default function ScientificDetail({ kind }: { kind: 'elements' | 'compounds' }) {
  const params = useParams();
  const id = (params.symbol ?? params.slug ?? '').toLowerCase();
  const { data, error, retry } = useScience<ScientificRecord>(kind, id);
  const [missing, setMissing] = useState(false);
  const [filter, setFilter] = useState('');
  const back = kind === 'elements' ? '/periodic' : '/compounds';
  if (!data) return <main className="science-detail"><Link to={back} className="science-text-link"><ArrowLeft size={16} /> Keşfe dön</Link><h1>{error ?? 'Bilimsel kayıt yükleniyor…'}</h1>{error && <button className="btn" onClick={retry}>Yeniden dene</button>}</main>;
  const names = data.names as Record<string, string>;
  const atom = data.atomic_properties as ScientificRecord | undefined;
  const molecular = data.molecular_properties as ScientificRecord | undefined;
  const provenance = data.provenance as ScientificRecord;
  const sections = Object.entries(data).filter(([key]) => labels[key]);
  const visible = sections.filter(([key]) => !filter || (labels[key] ?? key).toLocaleLowerCase('tr').includes(filter.toLocaleLowerCase('tr')));
  const mark = String(data.symbol ?? molecular?.molecular_formula ?? '');
  const download = () => { const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `${data.id}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  return <main className="science-detail">
    <Seo title={`${names.tr} (${mark}) · ElementAPI`} description={`${names.tr}: kaynaklı bilimsel özellikler, ayrıntılı veriler ve açık JSON kaydı.`} path={`/${kind === 'elements' ? 'element' : 'compound'}/${id}`} />
    <nav className="science-breadcrumb"><Link to={back}><ArrowLeft size={14} />{kind === 'elements' ? 'Periyodik tablo' : 'Bileşikler'}</Link><span>/</span><span>{names.tr}</span></nav>
    <header className="science-detail-hero"><div className={`science-specimen ${kind === 'compounds' ? 'is-molecule' : ''}`}><small>{String(data.atomic_number ?? 'MOLEKÜL')}</small><strong>{mark}</strong><span>{String(atom?.atomic_mass ?? molecular?.molecular_weight_g_mol ?? '—')} {atom ? 'u' : 'g/mol'}</span></div><div><p className="science-eyebrow">BİLİMSEL KAYIT · {String(data.id)}</p><h1>{names.tr}</h1><p className="science-detail-subtitle">{names.en}{names.iupac && names.iupac !== names.en ? ` · ${names.iupac}` : ''}</p><p className="science-detail-intro">{kind === 'elements' ? 'Atomik yapıdan izotoplara, bu elementin özelliklerini kaynaklarıyla keşfet.' : 'Molekülün kimliğini, ölçülmüş özelliklerini ve güvenlik kaynaklarını incele.'}</p><div className="science-detail-actions"><button onClick={download}><Download size={15} /> JSON indir</button><a href={scienceUrl(`${kind}/${id}`)} target="_blank" rel="noreferrer"><FileJson size={15} /> API kaydı <ArrowUpRight size={14} /></a></div></div><div className="science-detail-stamp"><span>KAYNAKLI AÇIK VERİ</span><strong>{String(provenance.retrieved_at)}</strong><span>Veri alım tarihi</span></div></header>
    <div className="science-detail-layout"><aside className="science-detail-nav"><p className="science-eyebrow">BU KAYITTA</p>{sections.map(([key, v]) => <a key={key} href={`#${key}`} onClick={() => setFilter('')}>{labels[key]}<span>{populated(v) ? '↗' : '—'}</span></a>)}<a href="#sources">Kaynaklar <ArrowUpRight size={13} /></a>{kind === 'elements' && <div className="science-market-links"><p>Simülasyonu keşfet</p><Link to={`/market?symbol=${mark}`}>Piyasa</Link><Link to={`/shop?symbol=${mark}`}>Mağaza</Link></div>}</aside>
      <div className="science-detail-content"><div className="science-data-tools"><label><Search size={16} /><input type="search" placeholder="Bölüm ara…" value={filter} onChange={e => setFilter(e.target.value)} aria-label="Bilimsel bölüm ara" /></label><label><input type="checkbox" checked={missing} onChange={e => setMissing(e.target.checked)} /> Eksik alanları göster</label></div><p className="science-data-note">“Veri yok”, bu kaynak sürümünde doğrulanmış değer bulunmadığını belirtir. Sıfır anlamına gelmez. Ölçüm koşulları ve belirsizlikler korunur.</p>
        {!visible.length && <p className="science-notice">Eşleşen bölüm bulunamadı.</p>}
        {visible.map(([key, value], index) => <section className="science-section" id={key} key={key}><header><span>{String(index + 1).padStart(2, '0')}</span><h2>{labels[key]}</h2></header>{key === 'isotopes' && <p className="science-data-note">NIST referans izotop bileşimleri. Doğal bolluk, kararlılık veya yarı ömür anlamına gelmez. Parantezli sayılar kaynak belirsizliğini korur.</p>}{key === 'safety' && <p className="science-data-note">Farklı tedarikçi, derişim ve deney koşullarına ait raporlar birlikte bulunabilir. Uygulama öncesinde kaynağı ve güncel ürün güvenlik bilgi formunu inceleyin.</p>}{key === 'thermodynamic_properties' && <p className="science-data-note">Yoğunluk için kaynakta belirtilmeyen STP koşulu varsayılmaz. Sıcaklık dönüşümü: °C = K − 273,15.</p>}<Value value={value} showMissing={missing} /></section>)}
        <section className="science-section" id="sources"><header><h2>Kaynaklar ve veri kapsamı</h2></header><p className="science-data-note">Veriler sürümlenmiş kaynak dosyalarından sunulur. Bilinmeyen alanlar tahminle doldurulmaz.</p><div className="science-source-cards">{(provenance.sources as ScientificRecord[]).map((s, i) => <a key={i} href={String(s.url)} target="_blank" rel="noreferrer"><strong>{String(s.name)} <ArrowUpRight size={15} /></strong><span>Alındı: {String(s.retrieved_at)}</span></a>)}</div></section>
        <details className="science-json"><summary><FileJson size={17} /> JSON kaydını görüntüle</summary><pre>{JSON.stringify(data, null, 2)}</pre></details>
      </div>
    </div>
  </main>;
}
